# Q1.

In [1]:
import numpy as np
import pandas as pd

In [2]:
#Q1. Pandas version

pd.__version__

'1.5.3'

In [3]:
data = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv"

In [4]:
df = pd.read_csv(data)

In [5]:
#   Q2. How many records are in the dataset? Answer = 9704

In [6]:
df

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369
...,...,...,...,...,...,...,...,...,...,...,...
9699,140,5.0,164.0,2981.107371,17.3,2013,Europe,Diesel,Front-wheel drive,NaN,15.101802
9700,180,NaN,154.0,2439.525729,15.0,2004,USA,Gasoline,All-wheel drive,0.0,17.962326
9701,220,2.0,138.0,2583.471318,15.1,2008,USA,Diesel,All-wheel drive,-1.0,17.186587
9702,230,4.0,177.0,2905.527390,19.4,2011,USA,Diesel,Front-wheel drive,1.0,15.331551
9703,270,3.0,140.0,2908.043477,14.7,2005,Asia,Diesel,All-wheel drive,-1.0,14.884467

In [7]:
# Q3 Answer = 2

In [8]:
df.fuel_type.unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [9]:
df.fuel_type.describe()

count         9704
unique           2
top       Gasoline
freq          4898
Name: fuel_type, dtype: object

In [10]:
#Q4 answer= 4

In [11]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [12]:
# Q5 what is the maximum fuel efficiency Anwer = 25.96722204888372

In [13]:
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [14]:
df.fuel_efficiency_mpg.mode()

0        6.200971
1        6.676475
2        6.695483
3        6.762991
4        6.805975
          ...
9699    23.369176
9700    23.556075
9701    23.759123
9702    24.971452
9703    25.967222
Name: fuel_efficiency_mpg, Length: 9704, dtype: float64

In [15]:
df.fuel_efficiency_mpg.max()

25.96722204888372

In [16]:
#Q6. Median value of horsepower

In [17]:
#Q6.1 Find the median value of horsepower column in the dataset. Anwer = 149.0

In [18]:
df.horsepower.median()

149.0

In [19]:
#Q6.2 Next, calculate the most frequent value of the same horsepower column. Answer = 152.0

In [20]:
df.horsepower.mode()

0    152.0
Name: horsepower, dtype: float64

In [21]:
#Q6.3 Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.

In [22]:
df.horsepower.isnull().sum()

708

In [23]:
df.horsepower.replace(' ', '152.0')

0       159.0
1        97.0
2        78.0
3         NaN
4       140.0
        ...
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [24]:
#Q6.4 Now, calculate the median value of horsepower once again.

In [25]:
df.horsepower.median()

149.0

In [26]:
#Q6 Has it changed? No

In [27]:
#Q7.1 Select all the cars from Asia

In [28]:
# Select all the cars from Asia, select only columns vehicle_weight and model_year
asia_cars = df[df["origin"] == "Asia"][["vehicle_weight", "model_year"]]
asia_cars

      vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [29]:

#Q7.3 Select the first 7 values (but there are only 5 rows and none are Asia)
X = asia_cars.head(7).to_numpy()

# X is empty because there are no Asia cars
print("X is empty:", X)

X is empty: [[2714.21930965 2016.        ]
 [2783.86897424 2010.        ]
 [3582.68736772 2007.        ]
 [2231.8081416  2011.        ]
 [2659.43145076 2016.        ]
 [2844.22753389 2014.        ]
 [3761.99403819 2019.        ]]

In [30]:
# Select rows where origin is "Asia"
asia_rows = df[df["origin"] == "Asia"]

print(asia_rows)

      engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310
12                    320            5.0       145.0     2783.868974
14                    200            6.0       160.0     3582.687368
20                    150            3.0       197.0     2231.808142
21                    160            4.0       133.0     2659.431451
...                   ...            ...         ...             ...
9688                  260            4.0         NaN     3948.404625
9692                  180            3.0       188.0     3680.341381
9693                  280            2.0       148.0     2545.070139
9698                  180            1.0       131.0     3107.427820
9703                  270            3.0       140.0     2908.043477

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0
...            ...         ...    ...       ...                ...        ...
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0

      fuel_efficiency_mpg
8               16.823554
12              16.175820
14              11.871091
20              18.889083
21              16.077730
...                   ...
9688            11.054830
9692            11.711653
9693            17.202782
9698            13.933716
9703            14.884467

[3247 rows x 11 columns]

In [31]:
# Compute matrix-matrix multiplication between the transpose of X and X
if X.size == 0:
    XTX = np.array([])  # or handle as needed for empty array
else:
    XTX = X.T @ X

In [32]:

# Invert XTX
if XTX.size == 0:
 XTX_inv = np.array([])  # Handling for empty
else:
    try:
        XTX_inv = np.linalg.inv(XTX)
    except np.linalg.LinAlgError:
        XTX_inv = np.array([])  # Handle singular matrix

In [33]:


# Create an array y
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [34]:

# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y
if X.size == 0 or XTX_inv.size == 0:
    w = np.array([])  # Because X is empty
else:
    w = XTX_inv @ X.T @ y

In [35]:

# Sum of all elements of w
if w.size == 0:
    sum_w = 0
else:
    sum_w = np.sum(w)

print("Sum of w:", sum_w)

Sum of w: 0.5187709081074046